version: '3.8'

services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: aml-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Gateway Service
  gateway:
    build: ./services/gateway
    container_name: aml-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - INGESTION_SERVICE_URL=http://ingestion:8001
      - ALERT_MANAGER_URL=http://alert-manager:8005
    depends_on:
      - ingestion
      - alert-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ingestion Service
  ingestion:
    build: ./services/ingestion
    container_name: aml-ingestion
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Feature Engineering Service
  feature-engine:
    build: ./services/feature-engine
    container_name: aml-feature-engine
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Risk Scoring Service
  risk-scorer:
    build: ./services/risk-scorer
    container_name: aml-risk-scorer
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Graph Analysis Service
  graph-analysis:
    build: ./services/graph-analysis
    container_name: aml-graph-analysis
    ports:
      - "8004:8004"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alert Manager Service
  alert-manager:
    build: ./services/alert-manager
    container_name: aml-alert-manager
    ports:
      - "8005:8005"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro  # Mount .env file into container
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  rabbitmq_data:

networks:
  default:
    name: aml-network 